import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    // Để overwrite template field
    absolute: "",
    // Nếu child segments không set title, nó sẽ fallback về giá trị default
    default: "Nextjs default title",
    // Để tạo một template cho child segments, chỉ apply cho child segments
    template: "Edward | %s",

  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>Header</header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
